### ISSUE TITLE
Modernization tracker

### ISSUE THREAD

**Issue by danvk** [oldnyc/oldnyc.github.io#8]
Non-TypeScript modernization:

- [x] Un-vendor dependencies
- [ ] Update eslint, set up typescript-eslint
- [x] Switch from jQuery `$.Deferred` to native promises
- [x] Port to React / ReactRouter
- [x] Replace ZeroClipboard with a native solution
- [x] Replace direct Firebase access with a lambda function
- [ ] Run prettier
- [ ] Remove my maps API key from the repo
- [x] Set up webpack dev server
- [x] Replace calls to `String.prototype.substr`

TypeScript modernization:

- [x] Enable `strictNullChecks`
